"""Database Repositories for AI Multi-Docs Extraction Pipeline."""

from .batch_repo import (
    calculate_file_hash,
    check_duplicate_document,
    create_batch,
    create_page,
    update_page,
    update_page_status,
    update_pages_status_batch,
    get_batch_pages,
    get_unextracted_batches,
    get_unextracted_batch_pages,
    get_unextracted_chunk_indices,
    get_pages_for_chunk,
    update_chunk_status,
    get_unextracted_chunks_for_batch,
    get_pages_by_chunk,
    update_chunk_pages_status,
    get_page_by_id,
    get_pages_by_status,
    get_all_pages,
)

from .document_repo import (
    create_document,
    link_pages_to_document,
    get_document_by_id,
    get_document_pages,
    get_pending_documents,
    get_all_documents,
    update_document_to_approved,
    update_document_to_rejected,
    acquire_document_lock,
    renew_document_lock,
    release_document_lock,
    get_document_lock_status,
    update_document_status,
    update_document_to_failed,
    update_document_payload,
    update_document_metadata,
    search_documents,
)

from .receipt_repo import (
    insert_relational_receipt,
    get_receipt_by_document_id,
)

from .merchant_repo import (
    sanitize_short_name,
    check_short_name_duplicate,
    check_file_prefix_duplicate,
    match_merchant_by_file_prefix,
    get_or_create_merchant_auto,
    approve_merchant,
    ignore_merchant,
    get_merchants,
    get_pending_merchants,
    get_merchant,
    get_merchant_by_tax_id,
    upsert_merchant,
    match_merchant,
    delete_merchant,
    update_merchant_status,
    get_sources,
    update_source_active_status,
)

from .company_repo import (
    get_or_create_default_company,
    create_company,
    get_company,
    get_company_by_code,
    get_all_companies,
    update_company,
    delete_company,
    get_doc_types,
    update_doc_type_active_status,
)

from .user_repo import (
    create_user,
    get_user_by_id,
    get_user_by_email,
    list_users,
)

__all__ = [
    # Batch
    "calculate_file_hash",
    "check_duplicate_document",
    "create_batch",
    "create_page",
    "update_page",
    "update_page_status",
    "update_pages_status_batch",
    "get_batch_pages",
    "get_unextracted_batches",
    "get_unextracted_batch_pages",
    "get_unextracted_chunk_indices",
    "get_pages_for_chunk",
    "update_chunk_status",
    "get_unextracted_chunks_for_batch",
    "get_pages_by_chunk",
    "update_chunk_pages_status",
    "get_page_by_id",
    "get_pages_by_status",
    "get_all_pages",
    # Document
    "create_document",
    "link_pages_to_document",
    "get_document_by_id",
    "get_document_pages",
    "get_pending_documents",
    "get_all_documents",
    "update_document_to_approved",
    "update_document_to_rejected",
    "acquire_document_lock",
    "renew_document_lock",
    "release_document_lock",
    "get_document_lock_status",
    "update_document_status",
    "update_document_to_failed",
    "update_document_payload",
    "update_document_metadata",
    "search_documents",
    # Receipt
    "insert_relational_receipt",
    "get_receipt_by_document_id",
    # Merchant
    "sanitize_short_name",
    "check_short_name_duplicate",
    "check_file_prefix_duplicate",
    "match_merchant_by_file_prefix",
    "get_or_create_merchant_auto",
    "approve_merchant",
    "ignore_merchant",
    "get_merchants",
    "get_pending_merchants",
    "get_merchant",
    "get_merchant_by_tax_id",
    "upsert_merchant",
    "match_merchant",
    "delete_merchant",
    "update_merchant_status",
    "get_sources",
    "update_source_active_status",
    # Company
    "get_or_create_default_company",
    "create_company",
    "get_company",
    "get_company_by_code",
    "get_all_companies",
    "update_company",
    "delete_company",
    "get_doc_types",
    "update_doc_type_active_status",
    # User
    "create_user",
    "get_user_by_id",
    "get_user_by_email",
    "list_users",
]
