"""Data Transfer Objects (DTOs) for Voucher RPA Gateway API (Application Layer).

Provides strict Pydantic v2 validation models for UiPath Bot integration,
Lease Locks, Completion callbacks, and Express JSON payloads.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class VoucherGetNextRequest(BaseModel):
    """Request payload for leasing next pending voucher."""
    bot_id: Optional[str] = Field(default="uipath_bot", description="Identifier of the RPA Robot/Worker")
    target_system_id: str = Field(default="EXPRESS", description="Target ERP System ID (e.g. EXPRESS)")
    preview: bool = Field(default=False, description="If True, retrieves data without acquiring lease lock")


class VoucherCompleteRequest(BaseModel):
    """Request payload for reporting voucher posting completion."""
    erp_reference_no: Optional[str] = Field(default=None, description="Voucher number or reference generated by ERP")


class VoucherFailRequest(BaseModel):
    """Request payload for reporting voucher posting failure."""
    error_message: str = Field(..., min_length=1, description="Reason/Stack trace of failure from RPA Bot")


class VoucherLineItemDTO(BaseModel):
    """GL detail line item in lowercase format."""
    account_code: str = Field(..., description="GL Account Code")
    amount: float = Field(..., description="Expense amount for this line")
    description: Optional[str] = Field(default=None, description="Line item narration/description")


class VoucherPayloadDTO(BaseModel):
    """Clean canonical voucher payload in lowercase format for UiPath."""
    voucher_id: str = Field(..., description="Internal UUID of Journal Voucher")
    voucher_no: Optional[str] = Field(default=None, description="Pre-generated Voucher Number (e.g. OE260730001)")
    voucher_date: str = Field(..., description="Voucher Date in Thai Buddhist Era DD/MM/YY")
    vendor_code: str = Field(..., description="Vendor Master Code in Express")
    ref_bill_no: str = Field(..., description="Supplier Invoice Number truncated to max 14 chars")
    ref_bill_date: str = Field(..., description="Invoice Date in Thai Buddhist Era DD/MM/YY")
    vat_type_id: int = Field(..., description="Express VatTypeId: 2 (Exclusive), 1 (Inclusive), 0 (No VAT)")
    subtotal: float = Field(..., description="Amount before VAT")
    vat_amount: float = Field(..., description="VAT Amount")
    is_override_vat: int = Field(default=1, description="1 if manual VAT from bill overrides auto calculation")
    wht_no: Optional[str] = Field(default=None, description="WHT Certificate No in format YY/MM/NNN")
    wht_rate: float = Field(default=0.0, description="Withholding Tax Rate percentage")
    wht_amount: float = Field(default=0.0, description="Withholding Tax Amount")
    lines: List[VoucherLineItemDTO] = Field(default_factory=list, description="List of GL Line Items")


class VoucherResponseWrapper(BaseModel):
    """Standard API response wrapper."""
    status: str = Field(default="success", description="Outcome status ('success' or 'error')")
    message: str = Field(..., description="Human-readable response message")
    data: Optional[VoucherPayloadDTO] = Field(default=None, description="Voucher payload or None if queue is empty")
